---

- name: 'This will compute a while.'
  hosts: localhost
  connection: local

  become: true
  tasks:

  - block: # Install open-eid
    - name: 'Add public key'
      apt_key:
        id: 7B72F63542EC16AAB64A6B32BC0B6176E6C57850
        url: https://raw.githubusercontent.com/perguth/chromeos-welcome-to-estonia/main/RIA.key
    - name: 'Add repository'
      apt_repository:
        repo: deb https://installer.id.ee/media/ubuntu/ focal main
        filename: ria-repository
        update_cache: yes
    - name: 'Install dependency 1/2'
      apt:
        name: libxerces-c3.2
    - name: 'Get dependency 2/2'
      get_url:
        url: http://ftp.ee.debian.org/debian/pool/main/x/xalan/libxalan-c111_1.11-9_amd64.deb
        dest: /tmp/libxalan-c111_1.11-9_amd64.deb
        checksum: 79179c073c342742304b8112d800c5ccaf55c85e8e731995b806cf2329bdf123
    - name: 'Install dependency 2/2'
      apt:
        deb: /tmp/libxalan-c111_1.11-9_amd64.deb
    - name: 'Install open-eid'
      apt:
        name: open-eid
  - block: # Install Firefox and plugins
    - name: 'Install Firefox'
      deb:
        name: firefox-esr
    - name: 'Install the Web eID extension'
      firefox_addon:
        url: https://addons.mozilla.org/en-US/firefox/addon/web-eid-webextension/
  - block: # Install DigiDoc4 Client
    - name: 'Install build dependencies'
      apt:
        name:
          - cmake
          - qttools5-dev
          - libqt5svg5-dev
          - qttools5-dev-tools
          - libpcsclite-dev
          - libssl-dev
          - libdigidocpp-dev
          - libldap2-dev
          - gettext
          - pkg-config
    - name: 'Get source code'
      git:
        repo: https://github.com/open-eid/DigiDoc4-Client.git
        dest: /tmp/DigiDoc4-Client
    - name: 'Configure'
      shell:
        chdir: /tmp/DigiDoc4-Client
        cmd: cmake -B build -S .
    - name: 'Build and install'
      shell:
        chdir: /tmp/DigiDoc4-Client
        cmd: cmake --build build

  - block: # Initalize
    - name: 'Initalize open-eid'
      command:
        cmd: /usr/bin/esteid-update-nssdb
