---

- name: This will compute a while.
  hosts: localhost
  connection: local

  become: true
  tasks:

  - block: # Install Firefox and plugins
    - name: Install Firefox
      apt:
        name: firefox-esr
    - name: Print instructions 
      debug:
        msg:
        - "# MANUAL STEPS REQUIRED:"
        - ""
        - "1. Open Firefox"
        - "2. Install the following extension:"
        - "  https://addons.mozilla.org/en-US/firefox/addon/web-eid-webextension  "

  - block: # Install card software
    - name: De-armor GPG key
      shell: "cat RIA.key | gpg --yes --dearmor -o /usr/share/keyrings/ria-repository.gpg"
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
    - name: Add repository
      apt_repository:
        filename: example-reporia-repository
        repo: 'deb [signed-by=/usr/share/keyrings/ria-repository.gpg] https://installer.id.ee/media/ubuntu/ jammy main'
    - name: Install packages
      apt:
        name: [open-eid, opensc]
        update_cache: yes
    - name: Enable service
      systemd_service:
        name: pcscd
        enabled: true
        state: started
    - name: Print instructions
      ansible.builtin.debug:
        msg:
        - "# USAGE INSTRUCTIONS:"
        - ""
        - "Every time you want to connect"
        - "your card to your computer,"
        - "do it the following way:"
        - ""
        - "1. Connect your reader/card to your computer"
        - "2. Select 'Connect to Linux'"
        - "3. Open a terminal and run the following:"
        - "  sudo service pcscd restart  "
