---

- name: "ChromeOS: Welcome to Estonia"
  hosts: localhost
  connection: local

  become: true
  tasks:

  - block: # Install Firefox and plugins
    - name: Install Firefox
      apt:
        name: firefox-esr
    - name: Print instructions
      debug:
        msg:
        - "# MANUAL STEPS REQUIRED:"
        - ""
        - "1. Open Firefox"
        - "2. Install the following extension:"
        - "  https://addons.mozilla.org/en-US/firefox/addon/web-eid-webextension  "

  - block: # Install card software
    - name: Add public key
      apt_key:
        file: RIA.key
        id: A754225DA61EA549
    - name: Add repository
      apt_repository:
        repo: deb https://installer.id.ee/media/ubuntu/ jammy main
        filename: ria-repository
        update_cache: yes
    - name: Install packages
      apt:
        name: [open-eid, opensc, inotify-tools]
        update_cache: yes
    # inotify-tools is required for the system service below

  - block: # Install system service
    - name: Ensure USB folder exists
      file:
        path: /dev/bus/usb/
        state: directory
    - name: Create script folder
      file:
        path: /opt/chromeos-welcome-to-estonia
        state: directory
    - name: Copy script
      copy:
        src: monitor-usb.sh
        dest: /opt/chromeos-welcome-to-estonia/monitor-usb.sh
        mode: u+x
    - name: Copy service file
      copy:
        src: chromeos-welcome-to-estonia.service
        dest: /etc/systemd/system/chromeos-welcome-to-estonia.service
    - name: Enable service
      systemd_service:
        state: restarted
        enabled: true
        daemon_reload: true
        name: chromeos-welcome-to-estonia
